# Generated by Django 5.1 on 2024-09-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocareweb', '0007_alter_vehicle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocareweb.vehiclemodel'),
        ),
    ]
